@startuml
!define table(x) class x << (T,#FFAAAA) >>

' Define the tables without id(PK), created_at, updated_at
table(users) {
  --
  nickname : string
  email : string, unique: true
  encrypted_password : string
  name : string, null: false
  profile : text
  birthday : date
}

table(items) {
  --
  name : string
  description : text
  price : integer
  category_id : integer
  condition_id : integer
  shipping_cost_id : integer
  shipping_day_id : integer
  user_id : integer (FK)
}

table(orders) {
  --
  user_id : integer (FK)
  item_id : integer (FK)
}

table(addresses) {
  --
  order : references, null: false, foreign_key: true
  postal_code : string
  prefecture_id : integer
  city : string
  address : string
  building : string
  phone_number : string
}

' Define relationships
users ||--o{ items : "has_many"
users ||--o{ orders : "has_many"
items ||--o{ orders : "has_one"
orders ||--o{ addresses : "has_one"

@enduml